// ============================================
// CHAT TIMER - Page Maintenance + Countdown
// ============================================
function setCookie(n,v,d){let e='';if(d){const dt=new Date();dt.setTime(dt.getTime()+(d*24*60*60*1000));e='; expires='+dt.toUTCString()}document.cookie=n+'='+encodeURIComponent(v||'')+e+'; path=/'}
function getCookie(n){const ne=n+'=';const ca=document.cookie.split(';');for(let i=0;i<ca.length;i++){let c=ca[i];while(c.charAt(0)===' ')c=c.substring(1);if(c.indexOf(ne)===0)return c.substring(ne.length)}return null}
async function checkPageTimer(){const pid='chat';let t=null;try{const s=localStorage.getItem('pageTimers');if(s){const tm=JSON.parse(s);t=tm[pid]}if(!t){const ck=getCookie('pageTimers');if(ck){const tm=JSON.parse(decodeURIComponent(ck));t=tm[pid]}}if(!t){const ss=sessionStorage.getItem('pageTimers');if(ss){const tm=JSON.parse(ss);t=tm[pid]}}}catch(e){}if(t&&t>Date.now()){showMaintenanceMode(t);return false}return true}
function showMaintenanceMode(te){
    document.querySelector('.chat-header').style.display='none';document.querySelector('.chat-tabs').style.display='none';document.querySelector('.chat-body').style.display='none';
    document.body.insertAdjacentHTML('beforeend',`<div id="maintContainer" style="display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh;text-align:center;padding:20px"><div style="font-size:60px;color:#f39c12;margin-bottom:15px"><i class="fas fa-tools"></i></div><div style="font-size:18px;font-weight:bold;color:#f39c12;margin-bottom:8px">ယခုစာမျက်နှာကို ပြုပြင်မွမ်းမံနေပါသည်</div><div id="maintCountdown" style="font-size:26px;font-weight:bold;color:#f39c12;font-family:'Courier New',monospace;margin:12px 0">--:--:--</div><a href="/dashboard" style="display:inline-block;padding:10px 25px;background:#f39c12;color:#000;text-decoration:none;border-radius:6px;font-weight:bold;font-size:13px;margin-top:8px"><i class="fas fa-arrow-left"></i> ပင်မစာမျက်နှာသို့</a></div>`);
    const ce=document.getElementById('maintCountdown');function up(){const r=te-Date.now();if(r<=0){try{const s=localStorage.getItem('pageTimers');if(s){const tm=JSON.parse(s);delete tm['chat'];localStorage.setItem('pageTimers',JSON.stringify(tm))}setCookie('pageTimers','',-1);sessionStorage.removeItem('pageTimers')}catch(e){}location.reload();return}const ss=Math.floor(r/1000),h=Math.floor(ss/3600),m=Math.floor((ss%3600)/60),s=ss%60;ce.textContent=String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}up();setInterval(up,1000)}
async function checkPageAccess(){
    try{const r=await fetch('/api/admin/page_status');const d=await r.json();if(d.pages){const cp=d.pages.find(p=>p.id==='chat');if(cp&&cp.status==='off'){const ht=await checkPageTimer();if(ht===false)return false;
    document.querySelector('.chat-header').style.display='none';document.querySelector('.chat-tabs').style.display='none';document.querySelector('.chat-body').style.display='none';
    document.body.insertAdjacentHTML('beforeend','<div style="display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh;text-align:center;padding:20px"><div style="font-size:60px;color:#f39c12;margin-bottom:15px"><i class="fas fa-tools"></i></div><div style="font-size:18px;font-weight:bold;color:#f39c12;margin-bottom:8px">ယခုစာမျက်နှာကို ပြုပြင်မွမ်းမံနေပါသည်</div><a href="/dashboard" style="display:inline-block;padding:10px 25px;background:#f39c12;color:#000;text-decoration:none;border-radius:6px;font-weight:bold;font-size:13px"><i class="fas fa-arrow-left"></i> ပင်မစာမျက်နှာသို့</a></div>');return false}}return true}catch(e){return true}}
setInterval(async()=>{try{const r=await fetch('/api/admin/page_status');const d=await r.json();if(d.pages){const cp=d.pages.find(p=>p.id==='chat');if(cp&&cp.status==='off')location.reload()}}catch(e){}},30000);
