// ============================================
// CHAT GROUPS - Create, Join, Manage, Report
// ============================================
function openCreateGroupModal(){document.getElementById('groupName').value='';document.getElementById('groupModal').classList.add('active')}
async function createGroup(){const gn=document.getElementById('groupName').value.trim();if(!gn){showToast('Group name required',true);return}try{const r=await fetch('/api/chat/create_group',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:currentUser.id,groupName:gn,members:[]})});const d=await r.json();if(d.success){showToast('Group created!');closeModal('groupModal');loadGroupsList();loadRooms()}else{showToast(d.message||'Error',true)}}catch(e){showToast('Server error',true)}}

async function viewGroupInfo(gid){
    try{const r=await fetch('/api/chat/group_info',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:gid,userId:currentUser?.id})});const d=await r.json();
    if(!d.success){showToast('Group not found',true);return}
    let mh='';try{const mr=await fetch('/api/chat/group_members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:gid,userId:currentUser?.id})});const md=await mr.json();
    if(md.success&&md.members){mh='<div style="font-size:11px;color:rgba(255,255,255,0.5);margin-bottom:6px">Members ('+md.members.length+')</div>';md.members.forEach(m=>{let rb='';if(m.role==='owner')rb='<span class="member-badge owner">Owner</span>';else if(m.role==='admin')rb='<span class="member-badge admin">Admin</span>';else rb='<span class="member-badge member">Member</span>';mh+=`<div class="member-item" style="cursor:pointer" onclick="viewUserProfile(${m.user_id})"><img src="${m.avatar_url||''}" class="member-avatar" onerror="this.style.display='none'"><div style="flex:1"><b>@${escapeHtml(m.username)}</b></div>${rb}</div>`})}}catch(e){}
    let h='<div class="group-full-page"><div class="group-header-section">';if(d.avatar_url){h+=`<img src="${d.avatar_url}" class="group-avatar-large" onerror="this.outerHTML=\'<div class=group-avatar-large style=background:rgba(255,255,255,0.1);display:inline-flex;align-items:center;justify-content:center;font-size:30px;margin-bottom:8px>👥</div>\'">`}else{h+='<div class="group-avatar-large" style="background:rgba(255,255,255,0.1);display:inline-flex;align-items:center;justify-content:center;font-size:30px;margin-bottom:8px">👥</div>'}
    h+=`<h3 style="font-size:16px;margin-bottom:4px">${escapeHtml(d.room_name)}</h3><div style="font-size:9px;color:rgba(255,255,255,0.4);margin-bottom:8px">${d.member_count||0} members</div><div class="btn-row" style="margin-bottom:8px">`;
    if(d.is_member){h+=`<button class="btn btn-w" onclick="openRoom(${gid},'${escapeHtml(d.room_name)}','group');closeModal('groupInfoModal')">💬 Chat</button>`;if(d.user_role==='owner'||d.user_role==='admin'){h+=`<button class="btn btn-b" onclick="uploadGroupPic(${gid})">📷 Edit Pic</button>`}if(d.user_role==='owner'||d.user_role==='admin'){h+=`<button class="btn btn-b" onclick="showManageMembers(${gid});closeModal('groupInfoModal')">👥 Manage</button>`}}h+='</div>';
    if(d.is_member){h+=`<div style="margin-bottom:8px"><div class="username-search-wrap"><input type="text" id="groupAddSearch" placeholder="🔍 Search @username to add..." oninput="searchUserForGroupAdd(${gid})" autocomplete="off" style="width:100%;padding:8px;background:rgba(0,0,0,0.3);border:1px solid rgba(255,255,255,0.15);border-radius:6px;color:#fff;font-size:10px"><div class="username-dropdown" id="groupAddDropdown"></div></div></div>`}
    if(d.is_member&&d.user_role!=='owner'){h+=`<button class="btn btn-r" onclick="leaveGroup(${gid})" style="width:100%;margin-top:4px">🚪 Leave</button>`}
    if(d.user_role==='owner'){h+=`<button class="btn btn-r" onclick="deleteGroup(${gid})" style="width:100%;margin-top:4px">🗑️ Delete</button>`}
    if(!d.is_member){h+=`<button class="join-btn" onclick="joinGroup(${gid})" style="width:100%;margin-top:8px">➕ Join Group</button>`}
    h+='</div><div class="group-members-section">'+(mh||'<div style="text-align:center;color:rgba(255,255,255,0.3);padding:20px">No members</div>')+'</div></div>';
    document.getElementById('groupInfoContent').innerHTML=h;document.getElementById('groupInfoModal').classList.add('active')}catch(e){showToast('Error',true)}
}

async function searchUserForGroupAdd(gid){const q=document.getElementById('groupAddSearch').value.trim();const dd=document.getElementById('groupAddDropdown');if(q.length<1){dd.classList.remove('active');return}try{const r=await fetch('/api/chat/search_users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q})});const d=await r.json();if(d.users?.length){dd.innerHTML=d.users.map(u=>`<div class="username-dropdown-item">@${escapeHtml(u.username)} <span class="add-btn" onclick="addMemberToGroupDirect(${gid},${u.id})">+ Add</span></div>`).join('');dd.classList.add('active')}else{dd.innerHTML='<div class="username-dropdown-item">No users</div>';dd.classList.add('active')}}catch(e){}}
async function addMemberToGroupDirect(gid,uid){try{const r=await fetch('/api/chat/add_member',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:gid,userId:uid,requesterId:currentUser.id})});const d=await r.json();if(d.success){showToast('Added!');document.getElementById('groupAddSearch').value='';document.getElementById('groupAddDropdown').classList.remove('active');viewGroupInfo(gid)}else{showToast(d.message||'Error',true)}}catch(e){showToast('Server error',true)}}

async function joinGroup(gid){try{const r=await fetch('/api/chat/join_group',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:gid,userId:currentUser.id})});const d=await r.json();if(d.success){showToast('Joined!');closeModal('groupInfoModal');openRoom(gid,d.room_name,'group');loadGroupsList();loadRooms()}else{showToast(d.message||'Error',true)}}catch(e){}}
async function leaveGroup(gid){if(!confirm('Leave?'))return;try{const r=await fetch('/api/chat/leave_group',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:gid,userId:currentUser.id})});const d=await r.json();if(d.success){showToast('Left');closeModal('groupInfoModal');closeChat();loadGroupsList();loadRooms()}else showToast(d.message||'Error',true)}catch(e){showToast('Server error',true)}}
async function deleteGroup(gid){if(!confirm('Delete group?'))return;try{await fetch('/api/chat/delete_room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:gid,userId:currentUser.id})});showToast('Deleted');closeModal('groupInfoModal');closeChat();loadGroupsList();loadRooms()}catch(e){}}

async function showManageMembers(gid){
    document.getElementById('manageMembersContent').innerHTML='<div style="text-align:center;padding:20px;color:rgba(255,255,255,0.4)">Loading...</div>';
    document.getElementById('manageMembersModal').classList.add('active');
    document.getElementById('manageMembersModal').querySelector('.modal-box').style.maxWidth='95%';
    document.getElementById('manageMembersModal').querySelector('.modal-box').style.maxHeight='90vh';
    try{const r=await fetch('/api/chat/group_members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:gid,userId:currentUser.id})});const d=await r.json();
    if(!d.success){showToast(d.message||'Error',true);closeModal('manageMembersModal');return}
    let h='<div style="max-height:65vh;overflow-y:auto">';d.members.forEach(m=>{let a='';
    if(d.userRole==='owner'&&m.user_id!==currentUser.id){a+='<div style="display:flex;gap:3px;flex-wrap:wrap;margin-top:4px">';if(m.role==='member')a+=`<button class="btn btn-b" style="font-size:7px;padding:3px 6px;flex:0" onclick="promoteToAdmin(${gid},${m.user_id})">👑 Admin</button>`;if(m.role==='admin')a+=`<button class="btn btn-w" style="font-size:7px;padding:3px 6px;flex:0" onclick="demoteToMember(${gid},${m.user_id})">👤 Member</button>`;a+=`<button class="btn btn-r" style="font-size:7px;padding:3px 6px;flex:0" onclick="kickMember(${gid},${m.user_id})">🚫 Kick</button>`;a+=`<button style="font-size:7px;padding:3px 6px;flex:0;background:#e74c3c;color:#fff;border:none;border-radius:6px;cursor:pointer" onclick="banMemberAsk(${gid},${m.user_id})">⛔ Ban</button>`;a+=`<button class="btn btn-w" style="font-size:7px;padding:3px 6px;flex:0" onclick="transferOwner(${gid},${m.user_id})">⭐ Transfer</button>`;a+='</div>'}
    else if(d.userRole==='admin'&&m.user_id!==currentUser.id&&m.role==='member'){a+='<div style="display:flex;gap:3px;flex-wrap:wrap;margin-top:4px">';a+=`<button class="btn btn-r" style="font-size:7px;padding:3px 6px;flex:0" onclick="kickMember(${gid},${m.user_id})">🚫 Kick</button>`;a+=`<button style="font-size:7px;padding:3px 6px;flex:0;background:#e74c3c;color:#fff;border:none;border-radius:6px;cursor:pointer" onclick="banMemberAsk(${gid},${m.user_id})">⛔ Ban</button>`;a+='</div>'}
    let rb='';if(m.role==='owner')rb='<span class="member-badge owner">Owner</span>';else if(m.role==='admin')rb='<span class="member-badge admin">Admin</span>';else rb='<span class="member-badge member">Member</span>';
    h+=`<div class="member-item" style="flex-wrap:wrap"><img src="${m.avatar_url||''}" class="member-avatar" onerror="this.style.display='none'" onclick="viewUserProfile(${m.user_id})"><div style="flex:1;min-width:100px;cursor:pointer" onclick="viewUserProfile(${m.user_id})"><b>@${escapeHtml(m.username)}</b></div>${rb}${a}</div>`});h+='</div>';document.getElementById('manageMembersContent').innerHTML=h}catch(e){}
}

async function promoteToAdmin(gid,uid){const r=await fetch('/api/chat/promote_admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:gid,userId:uid,requesterId:currentUser.id})});const d=await r.json();if(d.success){showToast('Promoted!');showManageMembers(gid)}else{showToast(d.message||'Error',true)}}
async function demoteToMember(gid,uid){const r=await fetch('/api/chat/demote_member',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:gid,userId:uid,requesterId:currentUser.id})});const d=await r.json();if(d.success){showToast('Demoted!');showManageMembers(gid)}else{showToast(d.message||'Error',true)}}
async function kickMember(gid,uid){if(!confirm('⚠️ Kick this member?'))return;const r=await fetch('/api/chat/kick_member',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:gid,userId:uid,requesterId:currentUser.id})});const d=await r.json();if(d.success){if(uid===currentUser.id){showKickNotification()}else{showToast('✅ Member kicked!')}showManageMembers(gid);loadGroupsList()}else{showToast(d.message||'Error',true)}}
async function transferOwner(gid,uid){if(!confirm('⚠️ Transfer ownership? You will become Admin.'))return;const r=await fetch('/api/chat/transfer_owner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:gid,userId:uid,requesterId:currentUser.id})});const d=await r.json();if(d.success){showToast('Transferred!');showManageMembers(gid);loadGroupsList()}else{showToast(d.message||'Error',true)}}

async function reportGroup(){if(!currentRoom||currentRoomType!=='group')return;if(!confirm('Report?'))return;try{const r=await fetch('/api/chat/report_group',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:currentRoom,userId:currentUser.id})});const d=await r.json();if(d.success){if(d.warning){showReportWarning(currentRoom)}else{showToast('Reported ('+d.reportCount+'/50)')}}else{showToast(d.message||'Already reported',true)}}catch(e){}}
function showReportWarning(rid){const ov=document.getElementById('reportWarningOverlay');ov.classList.add('active');let c=10;const el=document.getElementById('reportCountdown');el.textContent=c;const iv=setInterval(()=>{c--;el.textContent=c;if(c<=0){clearInterval(iv);ov.classList.remove('active');deleteGroupAfterReport(rid)}},1000)}
async function deleteGroupAfterReport(rid){try{await fetch('/api/chat/delete_room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:rid,userId:currentUser.id})});showToast('Deleted');closeChat();loadGroupsList();loadRooms()}catch(e){}}

function showKickNotification(){const overlay=document.createElement('div');overlay.id='kickNotification';overlay.style.cssText='position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.9);z-index:6000;display:flex;justify-content:center;align-items:center;flex-direction:column';overlay.innerHTML=`<div style="text-align:center;padding:30px"><div style="font-size:60px;margin-bottom:15px">🚫</div><div style="font-size:18px;font-weight:bold;color:#e74c3c;margin-bottom:8px">သင့်ကို Owner/Admin မှ ကန်ထုတ်လိုက်ပါသည်</div><div style="font-size:13px;color:rgba(255,255,255,0.6);margin-bottom:20px">You have been kicked from this group</div><div id="kickCountdown" style="font-size:40px;font-weight:bold;color:#f39c12;font-family:'Courier New',monospace">5</div><div style="font-size:10px;color:rgba(255,255,255,0.3);margin-top:8px">စက္ကန့်အတွင်း Group မှ ထွက်သွားပါမည်</div></div>`;document.body.appendChild(overlay);let count=5;const cd=document.getElementById('kickCountdown');const iv=setInterval(()=>{count--;cd.textContent=count;if(count<=0){clearInterval(iv);overlay.remove();closeChat();loadGroupsList();loadRooms();showToast('🚫 You have been kicked')}},1000)}
